layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: karim.zakariaa
  # linkedin: kareemzakaria
  # medium: @your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdgS-rGAcMkrsbVhCl1qrfW0sPtEQYrfCZqsJOuUNSRiPt0eBU

  - name: WebApi
    web_url: https://github.com/topics/webapi-2
    image_url: https://www.hopetutors.com/wp-content/uploads/2017/03/webapi-training-in-chennai.png

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/000/300/full/angular2.png
